### ISSUE TITLE
Form field attributes are not applied if inline_editable: true

### ISSUE THREAD

**Issue by jellygnite** [silverstripe/silverstripe-elemental#891] opened 2021-04-10 04:02 UTC
I wanted to apply a ```data-attribute="something"``` to some form fields on an Element but noticed these don't get added when the Element has inline_editable set to true.

Is this intentional?

It looks like the React component just isn't rendering the attributes. For now I have just set all my Elements to inline_editable: false but it would be great if data-attributes were applied on the inline forms.

**Comment by lerni** [comment] 2021-04-12 07:04
duplicate https://github.com/silverstripe/silverstripe-elemental/issues/738
yeah this is the #one reason I keep roll-out elements with inline_editable: false

**Comment by kinglozzer** [comment] 2021-04-12 08:12
Thanks both! Will close as a duplicate of https://github.com/silverstripe/silverstripe-elemental/issues/738

**Closed by kinglozzer** 2021-04-12 08:12 UTC
Labels: affects/v4, impact/medium, type/enhancement
