### ISSUE TITLE
Updating an elemental block does not trigger a change in history

### ISSUE THREAD

**Issue by nlighteneddesign** [silverstripe/silverstripe-elemental#910] opened 2021-06-24 19:18 UTC
When reordering or editing an elemental block the publish / save button does not turn green the way it does when you change a field.

If you change the order of an elemental block and review history the change is not timestamped.

**Comment by brynwhyman** [comment] 2021-07-21 02:10
Duplicate of: https://github.com/silverstripe/silverstripe-elemental/issues/790

See the last comment in that issue for a suggested better way to deal with versioning in the CMS (replace the versioned module). We're using the versioned-snapshots module on some significant production sites without issue.

**Closed by brynwhyman** 2021-07-21 02:10 UTC
Labels: affects/v4, impact/medium, type/enhancement
