### ISSUE TITLE
DOCS/BUG? provideBlockSchema() fileUrl doesn't work - must be fileURL

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-elemental#883] opened 2021-03-10 13:29 UTC
Ran into an issue today where I was passing the 'fileUrl' key rather than 'fileURL'.  fileUrl is used throughout the JS except https://github.com/silverstripe/silverstripe-elemental/blob/817c49c6f8395a33919b69138352c79db50f15c7/client/src/components/ElementEditor/Element.js#L236

Wonder if this should be fixed for consistency or documented somewhere?

**Comment by emteknetnz** [comment] 2021-03-18 07:06
Probably too risky to fix just for consistency, likely that it will cause regressions.

I could only find one other reference to `fileURL` and that was in here in this module https://github.com/silverstripe/silverstripe-elemental-fileblock/blob/2/src/Block/FileBlock.php#L64

Likely that if we updated this here then it would break this module at least, and potentially others that have it set to `fileURL`

I cannot think of a reasonable way forward here I'll close this issue for now

**Closed by emteknetnz** 2021-03-18 07:06 UTC

**Comment by christopherdarling** [comment] 2021-03-18 09:02
I'm surprised it's being closed but not resolved, could easily be resolved without any BC issues in https://github.com/silverstripe/silverstripe-elemental/blob/2ca21faaf39cbb80efd1f749b0243ce4b8037bdf/src/Models/BaseElement.php#L847 to alias the fileUrl to fileURL for now. Happy to raise a PR if that'll be accepted.

**Comment by GuySartorelli** [comment] 2021-07-21 01:58
This should _definitely_ either be fixed as per @christopherdarling's recommendation or at the very least clearly documented. I just spent a good 30 minutes trying to figure out what I was doing wrong and it was caused by this.
