### ISSUE TITLE
Support validation within in-line edit context

### ISSUE THREAD

**Issue by ScopeyNZ** [silverstripe/silverstripe-elemental#699] opened 2019-07-23 01:34 UTC
## Description

Currently the in-line editing editor and forms provide no detail on errors that have been added with `validate()` or via a form validator returned from `getCMSCompositeValidator()`.

## Investigation

See #688. Specifically https://github.com/dnadesign/silverstripe-elemental/issues/688#issuecomment-511754786 . 

There's also an investigation branch: 

https://github.com/creative-commoners/silverstripe-elemental/tree/pulls/4.1/validation-refactor

## A/Cs:

- [ ] Errors added using `addError($message)` appear on a block level within the in-line edit form after saving an individual block
- [ ] Errors added using `addError($message)` appear on a block level within the in-line edit form after saving the page as a whole
- [ ] Errors added using `addFieldError($field, $message)` appear on a form field (holder) level within the in-line edit form after saving an individual block
- [ ] Errors added using `addFieldError($field, $message)` appear on a form field (holder) level within the in-line edit form after saving the page as a whole
- [ ] When saving pages, all blocks are processed and those that are valid are correctly saved.
- [ ] When saving individual blocks, the block being saved is processed and if validation messages are displayed as appropriate
- [ ] Blocks that aren't saved keep their unsaved changes
- [ ] The unsaved changes indicator remains on invalid & unsaved blocks

**Comment by GuySartorelli** [comment] 2022-02-10 05:17
Also relevant: #329

**Comment by GuySartorelli** [comment] 2023-05-11 23:24
> When saving pages, all blocks are processed and those that are valid are correctly saved.

I don't think this is an appropriate behaviour. When saving a page, if one field is valid and another is invalid, the valid field doesn't get saved to the record. Similarly, when saving a page, an elemental block should be treated as a series of fields belonging to that page.
Otherwise you might get a scenario where one block references content from another block, and only one of those blocks is valid - we probably don't want the page to show partially-correct content.

**Comment by maxime-rainville** [comment] 2024-03-21 08:58
Duplicate of https://github.com/silverstripe/silverstripe-elemental/issues/329

**Closed by maxime-rainville** 2024-03-21 08:58 UTC
Labels: type/enhancement, affects/v4, complexity/high, impact/high

**Comment by GuySartorelli** [comment] 2024-03-21 20:38
@maxime-rainville Wasn't this the card we're using to track fixing up the UI?
#329 is just about getting the **functionality** working, but the UI will not be in a 100% ideal state after that card has been finished.

**Comment by maxime-rainville** [comment] 2024-03-25 22:01
I would rather use this card to track the UI changes related to Elemental validation

https://github.com/silverstripe/silverstripe-elemental/issues/1145
