### ISSUE TITLE
setAttribute doesn't work in inline_editable=true

### ISSUE THREAD

**Issue by lerni** [silverstripe/silverstripe-elemental#738] opened 2019-10-02 08:55 UTC
With 4.2.1 `$ElementBlahField->setAttribute('placeholder', $placeholdertext);` just shows if inline_editable=false.

**Comment by ScopeyNZ** [comment] 2019-10-03 18:43
This will probably be a bug with something in admin, but I don't have time to investigate now.

**Comment by kinglozzer** [comment] 2019-10-04 08:34
Sounds very related to https://github.com/silverstripe/silverstripe-framework/issues/9124

**Comment by blueskies79** [comment] 2019-11-03 18:38
I have no idea of the cause, so I can't say anything sensible on that. But I can confirm this issue exists. I tried to get a dependant dropdown (sheadawson/silverstripe-dependentdropdownfield) to work inside an elemental form and the setAttributes are missing. I can't get any setAttributes to show on Elemental formfields

**Comment by Rhym** [comment] 2020-03-10 01:16
This issue seems to still be prevalent.

**Comment by micschk** [comment] 2021-11-24 06:17
Temporary workaround (eg for placeholder attribute):
`$field->setSchemaData(['attributes' => ['placeholder' => 'My placeholder value']]);`

**Comment by GuySartorelli** [comment] 2024-05-24 00:51
This is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/9124 - once that's resolved, this will be resolved.

**Closed by GuySartorelli** 2024-05-24 00:51 UTC
Labels: type/bug, affects/v4, complexity/medium, impact/medium
